- include_tasks: apt.yml

- name: configure root bashrc
  template:
    src: root_bashrc.j2
    dest: "/root/.bashrc"
    mode: '0644'
  tags: configuration

- name: copy up logrotate config
  copy:
    src: "{{ item.file }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - { dest: "/etc", file: "logrotate.conf" }
    - { dest: "/root", file: ".inputrc" }
    - { dest: "/root", file: ".editrc" }

- name: copy up logrotate.d
  copy:
    src: logrotate.d
    dest: /etc/
    owner: root
    group: root
    mode: "0644"
