---
required_packages:
  - acl
  - cmake
  - g++
  - gcc
  - git
  - libjemalloc2
  - libc-dev
  - libffi-dev
  - libvips-dev
  - libyaml-dev
  - libmariadb-dev-compat
  - libmariadb-dev
  - libsqlite3-dev
  - libssl-dev
  - libreadline-dev
  - zlib1g-dev
  - make
  - mariadb-client
  - nodejs
  - pkg-config
  - rbenv
  - ruby-build
  - rustc
  - wrk
