- include_tasks: apt.yml

- name: mariadb config files
  register: mariadb_config
  copy:
    src: mysql
    dest: /etc/
    owner: root
    group: root
    mode: '0644'

- name: debian-start permission
  file:
    path: /etc/mysql/debian-start
    mode: u=rwx,g=rx,o=rx

- name: Use new config
  when: mariadb_config.changed
  systemd:
    name: mariadb
    state: restarted

- name: Enable mariadb at startup
  systemd:
    name: mariadb
    enabled: yes

- name: create dir for systemd override
  file:
    path: /etc/systemd/system/mariadb.service.d
    state: directory

- name: mariadb systemd config
  copy:
    src: restart.conf
    dest: /etc/systemd/system/mariadb.service.d/restart.conf
    owner: root
    group: root
    mode: 0600

- name: Create lobsters database
  community.mysql.mysql_db:
    name: lobsters_current
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create lobsters MariaDB user
  community.mysql.mysql_user:
    name: lobsters
    password: lobsters
    host: "{{ app_private_ip }}"
    priv: "lobsters_current.*:ALL"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
